version: 2

# Node image 
node_env: &node_env
  docker:
    - image: circleci/node:6.14.3-stretch-browsers

# Python image to run aws utilities
python_env: &python_env
  docker:
    - image: circleci/python:2.7-stretch-browsers

# Instructions of installing aws utilities
install_awscli: &install_awscli
  name: "Install awscli"
  command: |
    sudo pip install awscli awsebcli --upgrade
    aws --version
    eb --version

install_deploysuite: &install_deploysuite
  name: Installation of install_deploysuite.
  command: |
    git clone --branch v1.3 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
    cp ./../buildscript/master_deploy.sh .
    cp ./../buildscript/buildenv.sh .
    cp ./../buildscript/awsconfiguration.sh .
  
# Instructions of deployment
deploy_steps: &deploy_steps
  - checkout
  - attach_workspace:
      at: .
  - run: *install_awscli
  - run: *install_deploysuite
  - setup_remote_docker
  - run: docker build -t appiriodevops/tc-reporting-service:${DEPLOY_ENV}.${CIRCLE_BUILD_NUM} .
  - deploy:
      name: "configuring aws environment"
      command: |
        ./awsconfiguration.sh $DEPLOY_ENV  
        source awsenvconf
        ./buildenv.sh -e $DEPLOY_ENV -b ${DEPLOY_ENV}-tc-reporting-api-deployvar
        source buildenvvar
        ./master_deploy.sh -d EBS -e $DEPLOY_ENV -t "${DEPLOY_ENV}.${CIRCLE_BUILD_NUM}"
  #- run: .deploy/ebs_deploy.sh tc-reporting-service $DEPLOY_ENV $CIRCLE_BUILD_NUM

jobs:
  build:
    <<: *node_env
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "package.json" }}
      # Note: "npm install" is a inference step, which is not declared expicitly 
      # in circleci 1.0 config, but will be exectued at running time
      - run: npm install
      - save_cache:
          key: node-modules-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules

  deploy_prod:
    <<: *python_env
    environment:
      DEPLOY_ENV: "PROD"
    steps: *deploy_steps

  deploy_dev:
    <<: *python_env
    environment:
      DEPLOY_ENV: "DEV"
    steps: *deploy_steps

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_dev:
          filters:
            branches:
              only: [dev]
          requires:
            - build
      - deploy_prod:
          filters:
            branches:
              only: master
          requires:
            - build
