version: 2

# Node image 
node_env: &node_env
  docker:
    - image: circleci/node:6.14.3-stretch-browsers

# Python image to run aws utilities
python_env: &python_env
  docker:
    - image: circleci/python:2.7-stretch-browsers

# Instructions of installing aws utilities
install_awscli: &install_awscli
  name: "Install awscli"
  command: |
    sudo pip install awscli awsebcli --upgrade
    aws --version
    eb --version
  
# Instructions of deployment
deploy_steps: &deploy_steps
  - checkout
  - attach_workspace:
      at: .
  - run: *install_awscli
  - setup_remote_docker
  - run: .deploy/ebs_deploy.sh tc-reporting-service $DEPLOY_ENV $CIRCLE_BUILD_NUM

jobs:
  build:
    <<: *node_env
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "package.json" }}
      # Note: "npm install" is a inference step, which is not declared expicitly 
      # in circleci 1.0 config, but will be exectued at running time
      - run: npm install
      - save_cache:
          key: node-modules-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules

  deploy_prod:
    <<: *python_env
    environment:
      DEPLOY_ENV: "PROD"
    steps: *deploy_steps

  deploy_dev:
    <<: *python_env
    environment:
      DEPLOY_ENV: "DEV"
    steps: *deploy_steps

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_dev:
          filters:
            branches:
              only: [dev,dev-circleci2]
          requires:
            - build
      - deploy_prod:
          filters:
            branches:
              only: master
          requires:
            - build
